### PR TITLE
Avi fs tsv

### PR DESCRIPTION
**Pull request by AviFS**
Before submitting this Pull Request, please go thorugh the following checklist: 

---

Describe what this PR changes:

I'm afraid I submitted before this loaded in. I just fixed the formatting so that `table.tsv` renders correctly. There were 3 lines with `"` not escaped. However `Test'path/aplcart/table.tsv'` isn't working for me so I'm not sure...

---

If you've fixed [a logged issue](https://github.com/abrudz/APLcart/issues), complete the following line by putting the issue number to the immediate right of the # symbol:

Fixes #

---

If you've made changes to `table.tsv`:

- [ ] from your APL session, check that `Test'path/aplcart/table.tsv'` returns `1`
---

If you've made code or styling changes:

- [ ] Fire up a local server and check that the site functions properly.  
  For example, you can use [MiServer](https://github.com/Dyalog/MiServer/releases/latest):
  
  - `)load miserver.dws`
  - `Start'path/aplcart'`
  - Open [`localhost:8080`](http://localhost:8080/) in your browser

---

Thank you for your contribution to APLcart, @abrudz will have a look as soon as convenient.

### CODE REVIEW

**Comment by dzaima** [comment]
APLCart's table display isn't an actual tsv parser, it just lazily splits on newlines & tabs, so the quotes changed will be shown as-is in the entries.

**Comment by abrudz** [comment]
APLcart uses tabs, so quotes are not necessary and are instead taken literally. I'll amend the contributing instructions.

**Comment by AviFS** [comment]
@dzaima I was afraid that would be the case, which is why I wanted to test it... Oh well!

**Comment by abrudz** [comment]
I've added proper testing instructions: https://github.com/abrudz/aplcart/commit/c32bc045d658ce3b94164c793c32488d7b70fdfa

Also, the tsv format, including that one doesn't need to escape any symbols, is described: https://github.com/abrudz/aplcart/blob/master/CONTRIBUTING.md#contributing

**Pull request closed without merging**
